name: cart_state_manager
description: "Demo técnico - Gestión de estado de Riverpod y Freezed"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  freezed: ^2.4.2
  json_serializable: ^6.7.1